package us.tastybento.bskyblock.api.panels;

import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.Arrays;

public class PanelItem {

    private ItemStack item;
    private ClickHandler clickHandler;

    public PanelItem(ItemStack icon, String name, String description, boolean glow, ClickHandler clickHandler) {
        // Create the final item
        ItemMeta meta = icon.getItemMeta();
        meta.setDisplayName(name);
        meta.setLore(Arrays.asList(description.split("\\n"))); // the \n is automatically generated by the YAML when getting a multi-line value.

        // Set flags to neaten up the view
        meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
        meta.addItemFlags(ItemFlag.HIDE_DESTROYS);
        meta.addItemFlags(ItemFlag.HIDE_PLACED_ON);
        meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);

        if (glow) {
            meta.addEnchant(Enchantment.ARROW_DAMAGE, 0, true);
        }

        icon.setItemMeta(meta);

        // Assign the values
        this.item = icon;
        this.clickHandler = clickHandler;

        // if clickHandler is null, set a default one which will prevent picking up the item from the Panel
        if (this.clickHandler == null) {
            this.clickHandler = new ClickHandler() {
                @Override
                public boolean onClick(Player player, ClickType click) {
                    return false;
                }
            };
        }
    }

    public ItemStack getItem() {
        return item;
    }

    public ClickHandler getClickHandler() {
        return clickHandler;
    }

    public interface ClickHandler {
        boolean onClick(Player player, ClickType click);
    }
}
