/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        // Paper's repo hosts the paperweight 2.0.0-SNAPSHOT, required to read the data-version-8
        // dev bundles used by all Minecraft 26.x releases (no released paperweight supports them).
        maven("https://repo.papermc.io/repository/maven-public/") { name = "PaperMC" }
    }
}

rootProject.name = "bentobox"
