package world.bentobox.bentobox.commands;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

import world.bentobox.bentobox.api.addons.Addon;
import world.bentobox.bentobox.api.commands.CompositeCommand;
import world.bentobox.bentobox.api.user.User;
import world.bentobox.bentobox.managers.PlaceholdersManager;
import world.bentobox.bentobox.util.PlaceholderGrouper;
import world.bentobox.bentobox.util.PlaceholderGrouper.PlaceholderItem;

/**
 * Dumps all registered placeholders to a Markdown file.
 * <p>
 * Usage: {@code /bbox dump-placeholders}
 * </p>
 * <p>
 * The file is written to {@code plugins/BentoBox/placeholder-dump.md} and is
 * suitable for use as documentation on the BentoBoxWorld/docs site.
 * Placeholders are grouped by source (BentoBox core first, then addons sorted
 * alphabetically) and formatted as a Markdown table with columns for the full
 * placeholder string and its plain-English description.
 * </p>
 *
 * @since 3.2.0
 */
public class BentoBoxDumpPlaceholdersCommand extends CompositeCommand {

    public BentoBoxDumpPlaceholdersCommand(CompositeCommand parent) {
        super(parent, "dump-placeholders");
    }

    @Override
    public void setup() {
        setPermission("bentobox.admin.dump-placeholders");
        setOnlyPlayer(false);
        setDescription("commands.bentobox.dump-placeholders.description");
    }

    @Override
    public boolean execute(User user, String label, List<String> args) {
        File output = new File(getPlugin().getDataFolder(), "placeholder-dump.md");
        PlaceholdersManager pm = getPlugin().getPlaceholdersManager();

        try (PrintWriter writer = new PrintWriter(output, StandardCharsets.UTF_8)) {
            writer.println("# BentoBox Placeholders");
            writer.println();
            writer.println("_Generated by BentoBox v" + getPlugin().getDescription().getVersion()
                    + " on " + LocalDate.now() + "_");
            writer.println();

            // BentoBox core section
            Set<String> corePlaceholders = pm.getRegisteredBentoBoxPlaceholders();
            if (!corePlaceholders.isEmpty()) {
                String coreId = getPlugin().getName().toLowerCase();
                writer.println("## BentoBox");
                writer.println();
                writeTable(writer, pm, null, coreId, corePlaceholders);
            }

            // Addon sections, sorted alphabetically
            pm.getAddonsWithPlaceholders().stream()
                    .sorted(Comparator.comparing(a -> a.getDescription().getName()))
                    .forEach(addon -> {
                        Set<String> addonPlaceholders = pm.getRegisteredPlaceholders(addon);
                        if (!addonPlaceholders.isEmpty()) {
                            String addonId = addon.getDescription().getName().toLowerCase();
                            writer.println("## " + addon.getDescription().getName());
                            writer.println();
                            writeTable(writer, pm, addon, addonId, addonPlaceholders);
                        }
                    });

            user.sendMessage("commands.bentobox.dump-placeholders.dumped",
                    "[file]", output.getAbsolutePath());
        } catch (IOException e) {
            getPlugin().logError("Could not write placeholder dump: " + e.getMessage());
            user.sendMessage("commands.bentobox.dump-placeholders.error",
                    "[message]", e.getMessage());
            return false;
        }

        return true;
    }

    private void writeTable(PrintWriter writer, PlaceholdersManager pm, Addon addon,
            String expansionId, Set<String> placeholders) {
        // Group numeric series to avoid thousands of near-identical rows
        List<PlaceholderItem> items = PlaceholderGrouper.group(placeholders,
                key -> addon == null
                        ? pm.getPlaceholderDescription(key)
                        : pm.getPlaceholderDescription(addon, key));

        writer.println("| Placeholder | Description |");
        writer.println("|---|---|");
        items.forEach(item -> {
            String full = "`%" + expansionId + "_" + item.displayKey() + "%`";
            // For a series, append the numeric range to the description
            String description = item instanceof PlaceholderGrouper.Series ser
                    ? seriesDescription(ser)
                    : item.description();
            writer.println("| " + full + " | " + description + " |");
        });
        writer.println();
    }

    private static String seriesDescription(PlaceholderGrouper.Series ser) {
        String rangeNote = "(#" + ser.min() + " – #" + ser.max()
                + ", " + ser.rawKeys().size() + " items)";
        return ser.description().isBlank()
                ? rangeNote
                : ser.description() + " " + rangeNote;
    }
}
