name: BentoBox
main: world.bentobox.bentobox.BentoBox
version: ${project.version}
api-version: 1.13

authors: [tastybento, Poslovitch]
website: https://bentobox.world

softdepend: [Vault, PlaceholderAPI, MVdWPlaceholderAPI]

loadbefore: [Multiverse-Core]

permissions:    
  bentobox.admin:
   description: Allow bentobox command usage
   default: op
