name: BentoBox
main: world.bentobox.bentobox.BentoBox
version: ${project.version}${build.number}
api-version: "1.15"

authors: [tastybento, Poslovitch]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}

load: STARTUP

loadbefore: [Multiverse-Core, Residence]

softdepend: [Vault, PlaceholderAPI, dynmap, WorldEdit, WorldBorderAPI, BsbMongo, WorldGeneratorApi, AdvancedChests, LangUtils, WildStacker]

permissions:
  bentobox.admin:
    description: Allows most of bentobox commands usage
    default: op
    children:
      bentobox.admin.catalog:
        description: Allows to use /bentobox catalog
        default: op
      bentobox.admin.locale:
        description: Allows to use /bentobox locale
        default: op
      bentobox.admin.manage:
        description: Allows to use /bentobox manage
        default: op
      bentobox.admin.migrate:
        description: Allows to use /bentobox migrate
        default: op
      bentobox.admin.reload:
        description: Allows to use /bentobox reload
        default: op
  bentobox.about:
    description: Allows to use /bentobox about
    default: true
  bentobox.version:
    description: Allows to use /bentobox version
    default: op
